### ISSUE TITLE
Set activation date in the future

### ISSUE THREAD

**Issue by LeoOosterloo** [pronamic/wp-orbis-subscriptions#40]
When adding a new subscription the activation date is set on 'today'. Also when you set a date in the future, the activation date is saved as 'today'. 

Can this be fixed so we can activate a subscription in the future? This is useful when subscriptions are upgraded to a larger subscription on the renewal-date of the old subscription.

**Comment by remcotolsma** [comment]
This was challenging because the expiration date was always set directly, and it couldn’t be changed afterward due to dependencies in the renewal and billing system. However, we now have a background process, the 'Orbis Subscriptions Renewer,' that manages renewals daily, making things simpler and less error-prone. I believe it’s now safe to allow adjustments to the expiration and expiration date, though it’s best to avoid changes if the subscription has already been billed.

https://github.com/pronamic/wp-orbis-subscriptions/compare/db0edb8c658f262a78b2c5ebc4299ba0c25e1a10..8390e2aa9411803c77054a7aed8169e6ae972b5b
